name: "code quality PR check"

on:
  pull_request:
    paths:
      - "src/*"
      - "package-lock.json"
      - "tests/*"
      - "tsconfig.json"
      - .github/workflows/code-quality-pr-check.yml
    branches: [main]

jobs:
  lint-and-format-check:
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest", macos-latest']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"
      - name: Install Dependencies
        run: npm ci --ignore-scripts
      - name: lint
        run: npm run lint:ci
      - name: format check
        run: npm run format:ci
      - name: "run tests - ${{ matrix.os }}"
        run: npm run test:ci
      - uses: ./
        if: always()
        with:
          jobName: "lint-and-format-check"
          stepName: "run tests - ${{ matrix.os }}"
          path: "junit.xml"
          type: "junit"
          githubToken: ${{ secrets.GITHUB_TOKEN }}
  update-dist:
    runs-on: ubuntu-latest
    needs: [lint-and-format-check]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"
      - name: npm ci
        run: npm ci --omit=dev --ignore-scripts
      - name: tsc
        run: npm run package
      - name: commit dist
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Add dist artifacts
          file_pattern: dist
